### ISSUE TITLE
Invalid image file

### ISSUE THREAD

**Issue by kashifnaseer** [janko-m/shrine-cloudinary#1]
**Invalid image file** **500** error, for ALL **Other** than IMAGE (like doc, zip etc.) uploads. 

it works fine when I upload an Image file. Ideally it should give a validation error.

A piece of code is present below to understand it better.
      
    #Models
     class Vehicle < ActiveRecord::Base
         has_one :logo, ->  class_name: Photo
         accepts_nested_attributes_for :logo, update_only: true, reject_if: :all_blank, allow_destroy: true
       end

     class Photo < ActiveRecord::Base
       include ImageUploader[:image]
     end

    #Validation class    
    class ImageUploader < Shrine
      plugin :validation_helpers

      Attacher.validate do
        validate_mime_type_inclusion [/\Aimage/], message: "is not an image"
      end

      plugin :upload_options, store: ->(io, context) do
        formatted_photoable_type = context[:record].photoable_type.include?('Vehicle') ?      context[:record].photoable_type.titleize.split(' ')[0] : context[:record].photoable_type

      {
    	   tags: [context[:record].photoable_type, "#{formatted_photoable_type}-#{context[:record].photoable_id}"]
      }
      end
    end

and following Form:
     
     #form
     = simple_form_for @vehicle, url: vehicle_path(@vehicle), html: { enctype: "multipart/form-data" } do |f|
       = f.simple_fields_for :logo do |photo_form|
            = photo_form.input :image, label: false, input_html: { type: 'hidden', value: photo_form.object.cached_image_data }
            = photo_form.input :image, label: false, input_html: { class: "custom-file-input", required: true, type: 'file'" }

Any idea, how i can get a validation message rather 500 error, when anything other than image is uploaded ?

    @vehicle = Vehicle.find(params[:id])
    @vehicle.attributes = vehicle_params // It gives 500 error at this level 
    @vehicle.save // Should it not give a validation message here ?

**Comment by janko-m** [comment]
@kashifnaseer I'm assuming this error is coming from Cloudinary, right? This is most likely caused by the fact that `Shrine::Storage::Cloudinary` by default passes the `resource_type: "image"` when uploading files, so if you try to upload non-image files like .doc or .zip files, Cloudinary will complain because you told it that you're uploading images.

And raising an exception is the appropriate action here, because files should be validated before they actually reach the storage. However, I see that in your case this isn't possible because you're using Cloudinary as the temporary storage as well, and Shrine performs validations only on the cached file after it has been uploaded to permanent storage. And this is by design, it most likely isn't going to change.

You have several options of working around this issue (not mutually exclusive): 

(a) You can add the `accept` HTML attribute to the file field and specify allowed MIME types, so that when the user clicks on it and the file browser opens, they can select only files of that type (other types will be greyed out).

```haml
= simple_form_for @vehicle, url: vehicle_path(@vehicle), html: { enctype: "multipart/form-data" } do |f|
   = f.simple_fields_for :logo do |photo_form|
        = photo_form.input :image, label: false, input_html: { type: 'hidden', value: photo_form.object.cached_image_data }
        = photo_form.input :image, label: false, input_html: { accept: %w[image/jpeg image/png image/gif].join(","), class: "custom-file-input", required: true, type: 'file'"}
```

(b) You can add client-side validations which pops up an alert when selected file isn't an image file.

```js
$("your-file-input-selector").on("change", function(e) {
  var file = e.target.files[0];
  var image_types = ["image/jpeg", "image/png", "image/gif", ...];

  if (!image_types.includes(file.type)) {
    alert("The select file has to be one of: " + image_types.join(", "));
    e.target.val("") // remove the file from the input
  }
})
```

(c) Dynamically change the `resource_type` upload parameter to `raw` to allow upload of any file temporary storage, and then when your Shrine validations are triggered the user will get a validation error.

```rb
  plugin :upload_options,
    store: ->(io, context) do
      formatted_photoable_type = context[:record].photoable_type.include?('Vehicle') ?      context[:record].photoable_type.titleize.split(' ')[0] : context[:record].photoable_type

    {
	   tags: [context[:record].photoable_type, "#{formatted_photoable_type}-#{context[:record].photoable_id}"]
    }
    end,
    cache: ->(io, context) do
      image_extensions = %w[.jpg .jpeg .png .gif ...]
      extension = File.extname(io.to_io)

     { resource_type: image_extensions.include?(extension) ? "image" : "raw" }
    end
```

**Comment by kashifnaseer** [comment]
@janko-m great! it works. Thanks. But I noticed one thing. it still keeps the file (other than image) in cloudinary. How i can remove it from cloudinary, when validation fails ?

**Comment by janko-m** [comment]
You can just load the `remove_invalid` plugin, and it will automatically de-assign and delete the assigned file if the validation fails.
